<?php
echo '<!DOCTYPE html>';
echo '<html lang="pt-br">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="css/sim_style.css">';
echo '<link rel="stylesheet" href="css/sim_responsivity.css">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com">';
echo '<link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300&display=swap" rel="stylesheet">';
echo '<link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@300&display=swap" rel="stylesheet">';
echo '';
echo '<title>SIMULADOR DE COMPRA</title>';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="main">';
echo '<div class="title"><h3>SIMULADOR DE COMPRA</h3> </div>';
echo '<div class="item">';
echo '<label class="lab_basic" for="ipt_price">Valor do Produto</label><br>';
echo '<span class="real">R$';
echo '<input class="ipt_price" id="ipt_price" type="number" step="0.01" min="1" placeholder="0,00" ></span>';
echo '</div>';
echo '';
echo '<div class="item">';
echo '<label class="lab_basic" for="ipt_prepay">Entrada</label><br>';
echo '<span class="real">R$';
echo '<input class="ipt_prepay" id="ipt_prepay" type="number" step="1.00" min="1"  placeholder="0,00" > </span>';
echo '</div>';
echo '';
echo '<div class="item">';
echo '<label class="lab_basic" for="sel_installments">Número de parcelas</label><br>';
echo '<select class="sel_installments" id="sel_installments">';
echo '<option value="select">Selecione número de parcelas</option>';
echo '<option value="4.19">1</option>';
echo '<option value="6.00">2</option>';
echo '<option value="6.78">3</option>';
echo '<option value="7.6">4</option>';
echo '<option value="8.5">5</option>';
echo '<option value="9.25">6</option>';
echo '<option value="10.1">7</option>';
echo '<option value="11.00">8</option>';
echo '<option value="11.80">9</option>';
echo '<option value="12.20">10</option>';
echo '<option value="13.50">11</option>';
echo '<option value="14.40">12</option>';
echo '<option value="15.30">13</option>';
echo '<option value="16.20">14</option>';
echo '<option value="16.94">15</option>';
echo '<option value="17.90">16</option>';
echo '<option value="18.74">17</option>';
echo '<option value="19.68">18</option>';
echo '</select>';
echo '</div>';
echo '';
echo '<div class="result">';
echo '';
echo '</div>';
echo '';
echo '<div class="bt_div">';
echo '<button onClick="calc()" class="button" >CALCULAR</a>';
echo '<button onClick="window.location.reload()" class="button">LIMPAR</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<script src="js/logic.js"></script>';
echo '</body>';
echo '</html>';
?>